function [Effect] =Decision(A)
%%%%%%%%%SPLIT THE ACCURACIES INTO 2 Grpes
  G1=(A(:,1:3));
  G2=(A(:,4:end));
  [Max1,id1]=max(G1);
   [Max2,id2]=max(G2);
Effect=Max2-Max1;
%%%%%%%%
 M={'Zscore.','MinMax normalization.','Decimal Scaling.'};
CM={ 'ZOD and Decimal Scaling,Threshold=2.5,Opt=Mean.'...
    'ZOD and Decimal Scaling,Threshold=2.7,Opt=Mean.'...
    'ZOD and Decimal scaling,ThresholdT=2.9,Opt=Mean.'...
     'ZOD and Decimal Scaling,Threshold=3.1, Opt=Mean.'...
     'ZOD and Decimal Scaling,Threshold=3.3,Opt=Mean.'...
      'ZOD and Decimal Scaling,Threshold=3.5,Opt=Mean.'...
      'ZOD and Zscore,Threshold=2.5, Opt=Mean.'...
     'ZOD and Zscore,Threshold=2.7, Opt=Mean.'...
     'ZOD and Zscore,Threshold=2.9, Opt=Mean.'...
     'ZOD and Zscore,Threshold=3.1,Opt=Mean.'...
      'ZOD and Zscore,Threshold=3.3,Opt=Mean.'...
      'ZOD and Zscore,Threshold=3.5, Opt=Mean.'...
     'ZOD and MinMax,Threshold=2.5,Opt=Mean.'...
    'ZOD and MinMax,Threshold=2.7,Opt=Mean.'...
    'ZOD and MinMax,Threshold=2.9,Opt=Mean.'...
    'ZOD and MinMax,Threshold=3.1,Opt=Mean.'...
    'ZOD and MinMax,Threshold=3.3,Opt=Mean.'...
     'ZOD and MinMax,Threshold=3.5,Opt=Mean.'...
     'ZOD (Decimal scaling),Threshold=2.5,Opt=Median.'...
    'ZOD (Decimal scaling),Threshold=2.7,Opt=Median.'...
    'ZOD (Decimal scaling),Threshold=2.9, Opt=Median.'...
   'ZOD(Decimal scaling),Threshold=3.1,Opt=Median.'...
     'ZOD(Decimal scaling),Threshold=3.3,Opt=Median.'...
   'ZOD (Decimal scaling),Threshold=3.5,Opt=Median.'...
   'ZOD (Zscore),Threshold=2.5,Opt=Median.'...
   'ZOD (Zscore),Threshold=2.7,Opt=Median.'...
   'ZOD (Zscore),Threshold=2.9,Opt=Median.'...
   'ZOD (Zscore),Threshold=3.1,Opt=Median.'...
    'ZOD (Zscore),Threshold=3.3,Opt=Median.'...
      'ZOD (Zscore),Threshold=3.5,Opt=Median.'...
   'ZOD(MinMax), Threshold=2.5, Opt=Median.'...
   'ZOD(MinMax), Threshold=2.7, Opt=Median.'...
   'ZOD(MinMax), Threshold=2.9, Opt=Median.'...
   'ZOD(MinMax), Threshold=3.1, Opt=Median.'...
    'ZOD(MinMax), Threshold=3.3, Opt=Median.'...
   'ZOD(MinMax), Threshold=3.5, Opt=Median.'};

if Effect > 0
fprintf('Warning!!.The chained method is better than the classical Feature Scaling.\n\n')
for i=1:id2
if max(G2)==G2(1,i);
CM(:,i);
fprintf('The best method is chain of %s \n',CM{i});
fprintf('It performs at %.2f%% and has effect of %.2f%%\n\n',Max2, Effect);
for j1=1:id1
if max(G1)==G1(:,j1);
M(:,j1);
fprintf('The best classical feature scaling method was %s.\nIt has accuracy of %.2f%%\n',M{j1},Max1);
end
end
end
end
if Effect <0
fprintf('Warning !!Your proposed method is not better\n')
 for j=1:id1
if max(G1)==G1(:,j);
M(:,j);
fprintf('The best Classical method is %s\n',M{j});
fprintf('It performs at %.2f%%.\n',Max1);
end  
end
end
end